### ISSUE TITLE
The web page is down

### ISSUE THREAD

**Issue by Majncz** [tomasmcguinness/pkpassvalidator#25]
<img width="797" alt="image" src="https://github.com/user-attachments/assets/819fa9c5-ece7-413e-b5c4-269e19e9d952">
 This tool was my life saver, PLEASE fix this. I will forever be grateful 🙏🏼. Thanks a lot

**Comment by tomasmcguinness** [comment]
Sorry - Microsoft have disabled the AppService for some reason. I have opened a support request with them!

**Comment by ValerieMichaud** [comment]
Hopefuly this will come back soon!
I need a way to test one of my pkpass

**Comment by phlppnhllngr** [comment]
Would be great if Validator.cs could be released as a runnable binary so that we could do the validations offline.

**Comment by tomasmcguinness** [comment]
The Web application is back up!
