### ISSUE TITLE
Validator is checking the Issuer instead of the Subject of the WWDR cert

### ISSUE THREAD

**Issue by DuncWatts** [tomasmcguinness/pkpassvalidator#8]
I'm using the certificate downloaded from https://developer.apple.com/certificationauthority/AppleWWDRCA.cer and the subject does seem to match the wwdrCertSubject but the website is flagging this up as incorrect.

 result.WWDRCertificateSubjectMatches = appleWWDRCertificate.Issuer == wwdrCertSubject;

Is this correct or should I be using a different cert?

**Comment by tomasmcguinness** [comment]
Hi.

This is incorrect behavior. It always assumed that the first certificate extracted by the C# code is the WWDR one, which is no always the case.

I have a fix for that in the works, I just never got around to deploying it.

I should have something soon!

Tom

**Comment by tomasmcguinness** [comment]
I just pushed the updated version.

**Comment by DuncWatts** [comment]
Just retested and that's validating my pkpass, thank you very much
