### ISSUE TITLE
Ensure `authenticationToken` meets length requirements

### ISSUE THREAD

**Issue by mitchya1** [tomasmcguinness/pkpassvalidator#9]
According to the PassKit docs, `authenticationToken` must be at least 16 characters long. I spent a lot of time chasing my tail because `FOOBAR` < 16 characters. 

[Reference docs](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW3)

**Comment by tomasmcguinness** [comment]
Hi. 

Sorry that check wasn’t in there! I had a 16 character check on serial number, which I removed because it was not required. I must have misread the specification at the time!

I will add that check in as soon as possible.

Thank you for the coffee!! Very kind.

**Comment by mitchya1** [comment]
Sorry for not responding to this for almost a month!

Thanks for implementing this! Great work :)

**Comment by tomasmcguinness** [comment]
No problem. If you find this library useful, please consider sponsoring me - https://ko-fi.com/tomasmcguinness - thanks!
